services:
  astro-blog:
    build: .
    image: mikedev19/mikelabs-diglot:latest
    container_name: astro-blog
    restart: unless-stopped
    ports:
      - '4321:4321'
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: '4321'
      DATABASE_URL: file:/app/data/diglot.db
      AUTH_SECRET: ${AUTH_SECRET}
    volumes:
      - ./data:/app/data
